#! /bin/bash
# Call this script to check the format every c[pp] & h[pp] file
# in the current and parent directories against the defined clang-format style.
#
# Returns
# 0 on success
# 1 on an incorrect format

if command -v clang-format-8 > /dev/null; then
    BINARY="clang-format-8"
elif command -v clang-format > /dev/null; then
    BINARY="clang-format"
else
    echo "clang-format not found!"
    echo "Please install clang-format"
    exit 2
fi
echo "Using binary: $BINARY"

# Detect GNU parallel
if command -v parallel > /dev/null ; then
    echo "GNU parallel detected."
    HAS_PARALLEL=true
    PAROPS="--group "
    if [ -z "$CI" ]; then
      PAROPS="$PAROPS --bar"
    fi
else
    echo "Install GNU parallel to format in parallel."
    HAS_PARALLEL=false
fi

# Check C/C++
CFILES="$(find . -type f -name \*.hpp -or -name \*.h -or -name \*.cpp -or -name \*.c)"
echo "Checking $(echo "$CFILES" | wc -l) C/C++ files"
DIFFS=""
if $HAS_PARALLEL; then
    CMD="${BINARY} -style=file {} | grep '<replacement ' > /dev/null && echo {}"
    CDIFFS="$( echo "$CFILES" | parallel $PAROPS "$CMD" )"
    [[ -n "$CDIFFS" ]] && DIFFS="$DIFFS $CDIFFS"
else
    for cfile in $CFILES; do
        ${BINARY} -style=file --output-replacements-xml $cfile | grep '<replacement ' > /dev/null
        RET=$?
        if [ $RET -eq 0 ]; then
            DIFFS="$DIFFS $cfile"
        fi
    done
fi

if [[ -n "$DIFFS" ]]; then
    echo "The following files are not formatted correctly:"
    for file in $DIFFS; do
        echo "$file"
    done
    exit 1
else
    echo "All files are formatted correctly"
    exit 0
fi
